function restockRegs(amount)
	FindItem("Black Pearls", CLICKOBJ.OBJECTID)
	ContextMenu(FINDITEM[1].ID, "Split Stack")
	SetInput("StackSplit", "TextFieldStackAmount", tostring(amount))
	ClickButton("StackSplit",2)
	Dropc(BACKPACKID)
	sleep(333)
	FindItem("Blood Moss", CLICKOBJ.OBJECTID)
	ContextMenu(FINDITEM[1].ID, "Split Stack")
	SetInput("StackSplit", "TextFieldStackAmount", tostring(amount))
	ClickButton("StackSplit",2)
	Dropc(BACKPACKID)
	sleep(333)
	FindItem("Garlic", CLICKOBJ.OBJECTID)
	ContextMenu(FINDITEM[1].ID, "Split Stack")
	SetInput("StackSplit", "TextFieldStackAmount", tostring(amount))
	ClickButton("StackSplit",2)
	Dropc(BACKPACKID)
	sleep(333)
	FindItem("Mandrake Root", CLICKOBJ.OBJECTID)
	ContextMenu(FINDITEM[1].ID, "Split Stack")
	SetInput("StackSplit", "TextFieldStackAmount", tostring(amount))
	ClickButton("StackSplit",2)
	Dropc(BACKPACKID)
	sleep(333)
	FindItem("Nightshade", CLICKOBJ.OBJECTID)
	ContextMenu(FINDITEM[1].ID, "Split Stack")
	SetInput("StackSplit", "TextFieldStackAmount", tostring(amount))
	ClickButton("StackSplit",2)
	Dropc(BACKPACKID)
	sleep(333)
	FindItem("Spider's Silk", CLICKOBJ.OBJECTID)
	ContextMenu(FINDITEM[1].ID, "Split Stack")
	SetInput("StackSplit", "TextFieldStackAmount", tostring(amount))
	ClickButton("StackSplit",2)
	Dropc(BACKPACKID)
	sleep(333)
	FindItem("Sulfurous Ash", CLICKOBJ.OBJECTID)
	ContextMenu(FINDITEM[1].ID, "Split Stack")
	SetInput("StackSplit", "TextFieldStackAmount", tostring(amount))
	ClickButton("StackSplit",2)
	Dropc(BACKPACKID)
	sleep(333)
	FindItem("Ginseng", CLICKOBJ.OBJECTID)
	ContextMenu(FINDITEM[1].ID, "Split Stack")
	SetInput("StackSplit", "TextFieldStackAmount", tostring(amount))
	ClickButton("StackSplit",2)
	Dropc(BACKPACKID)
end

restockRegs(100)