function restockRegs(amount)
	FindItem("Black Pearls", CLICKOBJID)
	ContextMenu(FINDITEMID[1], "Split Stack")
	SetInput("StackSplit", "TextFieldStackAmount", tostring(amount))
	ClickButton("StackSplit",2)
	Dropc(BACKPACKID)
	sleep(333)
	FindItem("Blood Moss", CLICKOBJID)
	ContextMenu(FINDITEMID[1], "Split Stack")
	SetInput("StackSplit", "TextFieldStackAmount", tostring(amount))
	ClickButton("StackSplit",2)
	Dropc(BACKPACKID)
	sleep(333)
	FindItem("Garlic", CLICKOBJID)
	ContextMenu(FINDITEMID[1], "Split Stack")
	SetInput("StackSplit", "TextFieldStackAmount", tostring(amount))
	ClickButton("StackSplit",2)
	Dropc(BACKPACKID)
	sleep(333)
	FindItem("Mandrake Root", CLICKOBJID)
	ContextMenu(FINDITEMID[1], "Split Stack")
	SetInput("StackSplit", "TextFieldStackAmount", tostring(amount))
	ClickButton("StackSplit",2)
	Dropc(BACKPACKID)
	sleep(333)
	FindItem("Nightshade", CLICKOBJID)
	ContextMenu(FINDITEMID[1], "Split Stack")
	SetInput("StackSplit", "TextFieldStackAmount", tostring(amount))
	ClickButton("StackSplit",2)
	Dropc(BACKPACKID)
	sleep(333)
	FindItem("Spider's Silk", CLICKOBJID)
	ContextMenu(FINDITEMID[1], "Split Stack")
	SetInput("StackSplit", "TextFieldStackAmount", tostring(amount))
	ClickButton("StackSplit",2)
	Dropc(BACKPACKID)
	sleep(333)
	FindItem("Sulfurous Ash", CLICKOBJID)
	ContextMenu(FINDITEMID[1], "Split Stack")
	SetInput("StackSplit", "TextFieldStackAmount", tostring(amount))
	ClickButton("StackSplit",2)
	Dropc(BACKPACKID)
	sleep(333)
	FindItem("Ginseng", CLICKOBJID)
	ContextMenu(FINDITEMID[1], "Split Stack")
	SetInput("StackSplit", "TextFieldStackAmount", tostring(amount))
	ClickButton("StackSplit",2)
	Dropc(BACKPACKID)
end

restockRegs(100)