function restockRegs(amount)
    FindItem("Black Pearls", CLICKOBJID)
    SayCustom(".x use " .. FINDITEMID .. " Split Stack")
    SetInput("StackSplit", "TextFieldStackAmount", tostring(amount))
    ClickButton("StackSplit",2)
    Dropc(BACKPACKID)
    sleep(333)
    FindItem("Blood Moss", CLICKOBJID)
    SayCustom(".x use " .. FINDITEMID .. " Split Stack")
    SetInput("StackSplit", "TextFieldStackAmount", tostring(amount))
    ClickButton("StackSplit",2)
    Dropc(BACKPACKID)
    sleep(333)
    FindItem("Garlic", CLICKOBJID)
    SayCustom(".x use " .. FINDITEMID .. " Split Stack")
    SetInput("StackSplit", "TextFieldStackAmount", tostring(amount))
    ClickButton("StackSplit",2)
    Dropc(BACKPACKID)
    sleep(333)
    FindItem("Mandrake Root", CLICKOBJID)
    SayCustom(".x use " .. FINDITEMID .. " Split Stack")
    SetInput("StackSplit", "TextFieldStackAmount", tostring(amount))
    ClickButton("StackSplit",2)
    Dropc(BACKPACKID)
    sleep(333)
    FindItem("Nightshade", CLICKOBJID)
    SayCustom(".x use " .. FINDITEMID .. " Split Stack")
    SetInput("StackSplit", "TextFieldStackAmount", tostring(amount))
    ClickButton("StackSplit",2)
    Dropc(BACKPACKID)
    sleep(333)
    FindItem("Spider's Silk", CLICKOBJID)
    SayCustom(".x use " .. FINDITEMID .. " Split Stack")
    SetInput("StackSplit", "TextFieldStackAmount", tostring(amount))
    ClickButton("StackSplit",2)
    Dropc(BACKPACKID)
    sleep(333)
    FindItem("Sulfurous Ash", CLICKOBJID)
    SayCustom(".x use " .. FINDITEMID .. " Split Stack")
    SetInput("StackSplit", "TextFieldStackAmount", tostring(amount))
    ClickButton("StackSplit",2)
    Dropc(BACKPACKID)
    sleep(333)
    FindItem("Ginseng", CLICKOBJID)
    SayCustom(".x use " .. FINDITEMID .. " Split Stack")
    SetInput("StackSplit", "TextFieldStackAmount", tostring(amount))
    ClickButton("StackSplit",2)
    Dropc(BACKPACKID)
end

restockRegs(35)
